"""Domain enumeration types for mini me."""

from enum import Enum


class ProjectStatus(str, Enum):
    ACTIVE = "ACTIVE"
    DISABLED = "DISABLED"
    ARCHIVED = "ARCHIVED"


class ChangeStatus(str, Enum):
    DISCOVERED = "DISCOVERED"
    READY = "READY"
    IN_PROGRESS = "IN_PROGRESS"
    BLOCKED = "BLOCKED"
    DONE = "DONE"
    CANCELLED = "CANCELLED"


class ReadinessState(str, Enum):
    READY = "READY"
    NOT_READY = "NOT_READY"
    BLOCKED = "BLOCKED"


class AgentRole(str, Enum):
    IMPLEMENTER = "implementer"
    REVIEWER = "reviewer"
    AUDITOR = "auditor"
    HELPER = "helper"


class JobStatus(str, Enum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    CHECKS_RUNNING = "CHECKS_RUNNING"
    CHECKS_PASSED = "CHECKS_PASSED"
    CHECKS_FAILED = "CHECKS_FAILED"
    REVIEW_RUNNING = "REVIEW_RUNNING"
    AUDIT_RUNNING = "AUDIT_RUNNING"
    READY_TO_MERGE = "READY_TO_MERGE"
    AUDIT_BLOCKED = "AUDIT_BLOCKED"
    CHANGES_REQUIRED = "CHANGES_REQUIRED"
    WAITING_CAPACITY = "WAITING_CAPACITY"
    RECOVERY_BLOCKED = "RECOVERY_BLOCKED"
    NEEDS_HUMAN = "NEEDS_HUMAN"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class ExecutionOutcome(str, Enum):
    COMPLETED = "COMPLETED"
    CHANGES_REQUIRED = "CHANGES_REQUIRED"
    PREMATURE_STOP = "PREMATURE_STOP"
    FALSE_BLOCKER = "FALSE_BLOCKER"
    REAL_BLOCKER = "REAL_BLOCKER"
    NO_PROGRESS = "NO_PROGRESS"
    POLICY_VIOLATION = "POLICY_VIOLATION"
    MALFORMED_RESULT = "MALFORMED_RESULT"
    PROVIDER_FAILURE = "PROVIDER_FAILURE"
    PROVIDER_EXHAUSTED = "PROVIDER_EXHAUSTED"
    ENVIRONMENT_UNAVAILABLE = "ENVIRONMENT_UNAVAILABLE"
    EVIDENCE_INSUFFICIENT = "EVIDENCE_INSUFFICIENT"


class ContinuationDecision(str, Enum):
    CONTINUE_SAME_AGENT = "CONTINUE_SAME_AGENT"
    CORRECT_AND_RETRY = "CORRECT_AND_RETRY"
    REASSIGN_AGENT = "REASSIGN_AGENT"
    WAIT_EXTERNAL = "WAIT_EXTERNAL"
    NEEDS_HUMAN = "NEEDS_HUMAN"


class ProgressClassification(str, Enum):
    GOOD_PROGRESS = "GOOD_PROGRESS"
    PARTIAL_PROGRESS = "PARTIAL_PROGRESS"
    NO_PROGRESS = "NO_PROGRESS"
    REGRESSION = "REGRESSION"


class BlockerValidationVerdict(str, Enum):
    REAL_BLOCKER = "REAL_BLOCKER"
    FALSE_BLOCKER = "FALSE_BLOCKER"


class EvidenceDiagnosticStatus(str, Enum):
    PASS = "PASS"
    FAIL = "FAIL"
    SKIPPED_BY_POLICY = "SKIPPED_BY_POLICY"
    ENVIRONMENT_UNAVAILABLE = "ENVIRONMENT_UNAVAILABLE"
    EVIDENCE_NOT_REPRODUCIBLE = "EVIDENCE_NOT_REPRODUCIBLE"
    REVIEW_ENVIRONMENT_INVALID = "REVIEW_ENVIRONMENT_INVALID"


class PrimaryProvider(str, Enum):
    CODEX = "codex"
    ANTIGRAVITY = "antigravity"


PRIMARY_PROVIDERS: set[str] = {PrimaryProvider.CODEX.value, PrimaryProvider.ANTIGRAVITY.value}


class SchedulerMode(str, Enum):
    RUN = "RUN"
    DRAIN = "DRAIN"
    WAIT = "WAIT"


class ProviderHealthStatus(str, Enum):
    AVAILABLE = "available"
    TEMPORARILY_UNAVAILABLE = "temporarily_unavailable"
    EXHAUSTED = "exhausted"
    DEGRADED = "degraded"


class ProviderResultClass(str, Enum):
    SUCCESS = "success"
    TRANSIENT_ERROR = "transient_error"
    QUOTA_LIMIT = "quota_limit"
    RATE_LIMIT = "rate_limit"
    AUTH_ERROR = "auth_error"
    TIMEOUT = "timeout"
    MALFORMED_OUTPUT = "malformed_output"
    CANCELLED = "cancelled"
    POLICY_DENIED = "policy_denied"
    UNSAFE_BINDING = "unsafe_binding"
    UNKNOWN_ERROR = "unknown_error"
    BUDGET_DENIAL = "budget_denial"
    POLICY_DENIAL = "policy_denial"
    BUDGET_BREACH = "budget_breach"


class CapacitySignalSource(str, Enum):
    HEADER_RETRY_AFTER = "header_retry_after"
    RESPONSE_BODY_TIMESTAMP = "response_body_timestamp"
    UNKNOWN = "unknown"


class LockSafetyStatus(str, Enum):
    SAFE_ORPHANED = "SAFE_ORPHANED"
    ACTIVE_OWNER = "ACTIVE_OWNER"
    UNCERTAIN = "UNCERTAIN"
    EXTERNAL_OR_INVALID = "EXTERNAL_OR_INVALID"


class GitOperationStatus(str, Enum):
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    INTERRUPTED = "INTERRUPTED"
    RECOVERED = "RECOVERED"


class ReviewStatus(str, Enum):
    REVIEW_PENDING = "REVIEW_PENDING"
    REVIEW_RUNNING = "REVIEW_RUNNING"
    REVIEW_COMPLETED = "REVIEW_COMPLETED"
    REVIEW_FAILED = "REVIEW_FAILED"
    REVIEW_TIMED_OUT = "REVIEW_TIMED_OUT"


class ReviewVerdict(str, Enum):
    READY_TO_MERGE = "READY_TO_MERGE"
    CHANGES_REQUIRED = "CHANGES_REQUIRED"


class FindingSeverity(str, Enum):
    BLOCKER = "BLOCKER"
    MAJOR = "MAJOR"
    MINOR = "MINOR"


class AuditStatus(str, Enum):
    AUDIT_PENDING = "AUDIT_PENDING"
    AUDIT_RUNNING = "AUDIT_RUNNING"
    AUDIT_COMPLETED = "AUDIT_COMPLETED"
    AUDIT_BLOCKED = "AUDIT_BLOCKED"
    AUDIT_FAILED = "AUDIT_FAILED"
    AUDIT_TIMED_OUT = "AUDIT_TIMED_OUT"


class AuditRiskLevel(str, Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class AuditFindingSeverity(str, Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class EventType(str, Enum):
    PROJECT_REGISTERED = "PROJECT_REGISTERED"
    PROJECT_UPDATED = "PROJECT_UPDATED"
    CHANGE_DISCOVERED = "CHANGE_DISCOVERED"
    READINESS_EVALUATED = "READINESS_EVALUATED"
    WORK_BOUND = "WORK_BOUND"
    SYNC_FAILED = "SYNC_FAILED"
    SYNC_RECONCILED = "SYNC_RECONCILED"
    STATUS_CHECKED = "STATUS_CHECKED"
    JOB_QUEUED = "JOB_QUEUED"
    JOB_RUNNING = "JOB_RUNNING"
    JOB_CHECKS_RUNNING = "JOB_CHECKS_RUNNING"
    JOB_CHECKS_PASSED = "JOB_CHECKS_PASSED"
    JOB_CHECKS_FAILED = "JOB_CHECKS_FAILED"
    JOB_REVIEW_RUNNING = "JOB_REVIEW_RUNNING"
    JOB_AUDIT_RUNNING = "JOB_AUDIT_RUNNING"
    JOB_AUDIT_COMPLETED = "JOB_AUDIT_COMPLETED"
    JOB_AUDIT_BLOCKED = "JOB_AUDIT_BLOCKED"
    JOB_AUDIT_FAILED = "JOB_AUDIT_FAILED"
    JOB_READY_TO_MERGE = "JOB_READY_TO_MERGE"
    JOB_CHANGES_REQUIRED = "JOB_CHANGES_REQUIRED"
    JOB_WAITING_CAPACITY = "JOB_WAITING_CAPACITY"
    JOB_FAILED = "JOB_FAILED"
    JOB_CANCELLED = "JOB_CANCELLED"
    JOB_TIMEOUT = "JOB_TIMEOUT"
    INCOMPLETE_TASKS = "INCOMPLETE_TASKS"
    REVIEW_POLICY_VIOLATION = "REVIEW_POLICY_VIOLATION"
    REVIEW_TIMEOUT = "REVIEW_TIMEOUT"
    AUDIT_TIMEOUT = "AUDIT_TIMEOUT"
    CANDIDATE_SHA_MISMATCH = "CANDIDATE_SHA_MISMATCH"
    UNAUTHORIZED_REVIEWER_MUTATION = "UNAUTHORIZED_REVIEWER_MUTATION"
    UNAUTHORIZED_AUDITOR_MUTATION = "UNAUTHORIZED_AUDITOR_MUTATION"
    MALFORMED_REVIEW_OUTPUT = "MALFORMED_REVIEW_OUTPUT"
    AUDIT_MALFORMED_OUTPUT = "AUDIT_MALFORMED_OUTPUT"
    SCHEDULER_MODE_CHANGED = "SCHEDULER_MODE_CHANGED"
    PRIMARY_CAPACITY_EXHAUSTED = "PRIMARY_CAPACITY_EXHAUSTED"
    PRIMARY_CAPACITY_RECOVERED = "PRIMARY_CAPACITY_RECOVERED"
    PROVIDER_HEALTH_UPDATED = "PROVIDER_HEALTH_UPDATED"
    PROVIDER_PROBE_FAILED = "PROVIDER_PROBE_FAILED"
    DAEMON_RESTARTED = "DAEMON_RESTARTED"
    JOB_INTERRUPTED = "JOB_INTERRUPTED"
    JOB_RECOVERED = "JOB_RECOVERED"
    WORKTREE_LOCK_RECOVERED = "WORKTREE_LOCK_RECOVERED"
    RECOVERY_BLOCKED = "RECOVERY_BLOCKED"
    FALLBACK_INVOKED = "FALLBACK_INVOKED"
    BUDGET_RESERVED = "BUDGET_RESERVED"
    BUDGET_SETTLED = "BUDGET_SETTLED"
    BUDGET_CAP_EXCEEDED = "BUDGET_CAP_EXCEEDED"
    BUDGET_BREACH_DETECTED = "BUDGET_BREACH_DETECTED"
    FALLBACK_MODEL_SELECTED = "FALLBACK_MODEL_SELECTED"
    FALLBACK_DENIED = "FALLBACK_DENIED"
    ATTEMPT_STARTED = "ATTEMPT_STARTED"
    ATTEMPT_COMPLETED = "ATTEMPT_COMPLETED"
    COMPLETION_VERIFIED = "COMPLETION_VERIFIED"
    COMPLETION_REJECTED = "COMPLETION_REJECTED"
    BLOCKER_CLAIMED = "BLOCKER_CLAIMED"
    BLOCKER_VALIDATED = "BLOCKER_VALIDATED"
    CONTINUATION_DECIDED = "CONTINUATION_DECIDED"
    CORRECTIVE_RETRY_ISSUED = "CORRECTIVE_RETRY_ISSUED"
    AGENT_REASSIGNED = "AGENT_REASSIGNED"
    AGENT_PING_PONG_EXHAUSTED = "AGENT_PING_PONG_EXHAUSTED"
    HANDOFF_CREATED = "HANDOFF_CREATED"
    HANDOFF_CONSUMED = "HANDOFF_CONSUMED"
    CANDIDATE_MANIFEST_CREATED = "CANDIDATE_MANIFEST_CREATED"
    REVIEW_VISIBILITY_INVALID = "REVIEW_VISIBILITY_INVALID"
    EVIDENCE_DIAGNOSTIC_RECORDED = "EVIDENCE_DIAGNOSTIC_RECORDED"
    JOB_NEEDS_HUMAN = "JOB_NEEDS_HUMAN"
    ORCHESTRATION_STARTED = "ORCHESTRATION_STARTED"
    ORCHESTRATION_STAGE_TRANSITIONED = "ORCHESTRATION_STAGE_TRANSITIONED"
    ORCHESTRATION_STOPPED = "ORCHESTRATION_STOPPED"
    ORCHESTRATION_RESUMED = "ORCHESTRATION_RESUMED"
    ORCHESTRATION_RECOVERED = "ORCHESTRATION_RECOVERED"
    CANDIDATE_FROZEN = "CANDIDATE_FROZEN"
    CANDIDATE_SUPERSEDED = "CANDIDATE_SUPERSEDED"
    EXTERNAL_ACTION_RESERVED = "EXTERNAL_ACTION_RESERVED"
    EXTERNAL_ACTION_COMPLETED = "EXTERNAL_ACTION_COMPLETED"
    EXTERNAL_ACTION_FAILED = "EXTERNAL_ACTION_FAILED"
    EXTERNAL_ACTION_RECONCILED = "EXTERNAL_ACTION_RECONCILED"
    PR_PREPARED = "PR_PREPARED"
    READY_FOR_HUMAN_MERGE = "READY_FOR_HUMAN_MERGE"


class OrchestrationStage(str, Enum):
    ADMITTED = "ADMITTED"
    PREPARING_EXECUTION = "PREPARING_EXECUTION"
    IMPLEMENTING = "IMPLEMENTING"
    EVALUATING_ATTEMPT = "EVALUATING_ATTEMPT"
    RUNNING_CHECKS = "RUNNING_CHECKS"
    FREEZING_CANDIDATE = "FREEZING_CANDIDATE"
    COMPLEMENTARY_REVIEW = "COMPLEMENTARY_REVIEW"
    REVIEW_REMEDIATION = "REVIEW_REMEDIATION"
    INDEPENDENT_AUDIT = "INDEPENDENT_AUDIT"
    AUDIT_REMEDIATION = "AUDIT_REMEDIATION"
    PREPARING_PR = "PREPARING_PR"
    PR_PREPARED = "PR_PREPARED"


class OrchestrationStopOutcome(str, Enum):
    READY_FOR_HUMAN_MERGE = "READY_FOR_HUMAN_MERGE"
    WAITING_CAPACITY = "WAITING_CAPACITY"
    WAITING_EXTERNAL = "WAITING_EXTERNAL"
    NEEDS_HUMAN = "NEEDS_HUMAN"


class HumanGate(str, Enum):
    READY_FOR_HUMAN_MERGE = "READY_FOR_HUMAN_MERGE"
    NEEDS_HUMAN = "NEEDS_HUMAN"


class ExternalActionType(str, Enum):
    BRANCH_PUSH = "BRANCH_PUSH"
    PR_CREATE = "PR_CREATE"
    PR_UPDATE = "PR_UPDATE"


class ExternalActionStatus(str, Enum):
    RESERVED = "RESERVED"
    EXECUTING = "EXECUTING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    AMBIGUOUS = "AMBIGUOUS"
