"""Domain enumeration types for mini me."""

from enum import Enum


class ProjectStatus(str, Enum):
    ACTIVE = "ACTIVE"
    DISABLED = "DISABLED"
    ARCHIVED = "ARCHIVED"


class ProjectOnboardingStatus(str, Enum):
    UNBOUND = "UNBOUND"
    BINDING = "BINDING"
    CONTEXT_INCOMPLETE = "CONTEXT_INCOMPLETE"
    READY_FOR_WORK = "READY_FOR_WORK"
    BLOCKED = "BLOCKED"


class WorkItemStatus(str, Enum):
    BACKLOG = "BACKLOG"
    CONTEXT_CHECK = "CONTEXT_CHECK"
    PREPARING = "PREPARING"
    NEEDS_HUMAN = "NEEDS_HUMAN"
    READY = "READY"
    ADMITTED = "ADMITTED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    BLOCKED = "BLOCKED"
    CANCELLED = "CANCELLED"


class WorkItemSource(str, Enum):
    ROADMAP = "ROADMAP"
    LOCAL_BACKLOG = "LOCAL_BACKLOG"
    GITHUB_ISSUE = "GITHUB_ISSUE"
    MANUAL_INTAKE = "MANUAL_INTAKE"
    OPENSPEC_CHANGE = "OPENSPEC_CHANGE"


class ChangeStatus(str, Enum):
    DISCOVERED = "DISCOVERED"
    READY = "READY"
    IN_PROGRESS = "IN_PROGRESS"
    BLOCKED = "BLOCKED"
    DONE = "DONE"
    CANCELLED = "CANCELLED"


class ReadinessState(str, Enum):
    READY = "READY"
    NOT_READY = "NOT_READY"
    BLOCKED = "BLOCKED"


class AgentRole(str, Enum):
    IMPLEMENTER = "implementer"
    REVIEWER = "reviewer"
    AUDITOR = "auditor"
    HELPER = "helper"


class JobStatus(str, Enum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    CHECKS_RUNNING = "CHECKS_RUNNING"
    CHECKS_PASSED = "CHECKS_PASSED"
    CHECKS_FAILED = "CHECKS_FAILED"
    REVIEW_RUNNING = "REVIEW_RUNNING"
    AUDIT_RUNNING = "AUDIT_RUNNING"
    READY_TO_MERGE = "READY_TO_MERGE"
    POST_MERGE_RECONCILING = "POST_MERGE_RECONCILING"
    COMPLETED = "COMPLETED"
    AUDIT_BLOCKED = "AUDIT_BLOCKED"
    CHANGES_REQUIRED = "CHANGES_REQUIRED"
    WAITING_CAPACITY = "WAITING_CAPACITY"
    RECOVERY_BLOCKED = "RECOVERY_BLOCKED"
    NEEDS_HUMAN = "NEEDS_HUMAN"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class RemediationStatus(str, Enum):
    """Durable lifecycle states for an explicit preserved-candidate remediation."""

    ADMITTED = "ADMITTED"
    WORKSPACE_READY = "WORKSPACE_READY"
    IMPLEMENTER_RUNNING = "IMPLEMENTER_RUNNING"
    IMPLEMENTER_COMPLETED = "IMPLEMENTER_COMPLETED"
    SCOPE_VALIDATED = "SCOPE_VALIDATED"
    CANDIDATE_PERSISTED = "CANDIDATE_PERSISTED"
    SCOPE_FAILED = "SCOPE_FAILED"
    NO_PROGRESS = "NO_PROGRESS"
    FINALIZED = "FINALIZED"
    CHECKS_RUNNING = "CHECKS_RUNNING"
    CHECKS_FAILED = "CHECKS_FAILED"
    COMPLETED = "COMPLETED"
    NEEDS_HUMAN = "NEEDS_HUMAN"
    FAILED = "FAILED"


class RemediationFailureCode(str, Enum):
    """Stable operational codes emitted by preserved-candidate remediation."""

    AUTHORITY_MISMATCH = "REMEDIATION_AUTHORITY_MISMATCH"
    CONTRACT_INVALID = "REMEDIATION_CONTRACT_INVALID"
    SCOPE_VIOLATION = "REMEDIATION_SCOPE_VIOLATION"
    NO_PROGRESS = "REMEDIATION_NO_PROGRESS"
    PROVIDER_UNAVAILABLE = "REMEDIATION_PROVIDER_UNAVAILABLE"
    CHECKS_FAILED = "REMEDIATION_CHECKS_FAILED"
    PRESERVATION_FAILED = "REMEDIATION_PRESERVATION_FAILED"
    BASE_ADVANCED_REQUIRES_INTEGRATION = "BASE_ADVANCED_REQUIRES_INTEGRATION"
    BASE_INTEGRATION_CONFLICT = "BASE_INTEGRATION_CONFLICT"


class ExecutionOutcome(str, Enum):
    COMPLETED = "COMPLETED"
    CHANGES_REQUIRED = "CHANGES_REQUIRED"
    PREMATURE_STOP = "PREMATURE_STOP"
    FALSE_BLOCKER = "FALSE_BLOCKER"
    REAL_BLOCKER = "REAL_BLOCKER"
    NO_PROGRESS = "NO_PROGRESS"
    POLICY_VIOLATION = "POLICY_VIOLATION"
    MALFORMED_RESULT = "MALFORMED_RESULT"
    PROVIDER_FAILURE = "PROVIDER_FAILURE"
    PROVIDER_EXHAUSTED = "PROVIDER_EXHAUSTED"
    ENVIRONMENT_UNAVAILABLE = "ENVIRONMENT_UNAVAILABLE"
    EVIDENCE_INSUFFICIENT = "EVIDENCE_INSUFFICIENT"


class ContinuationDecision(str, Enum):
    CONTINUE_SAME_AGENT = "CONTINUE_SAME_AGENT"
    CORRECT_AND_RETRY = "CORRECT_AND_RETRY"
    REASSIGN_AGENT = "REASSIGN_AGENT"
    WAIT_EXTERNAL = "WAIT_EXTERNAL"
    NEEDS_HUMAN = "NEEDS_HUMAN"


class ProgressClassification(str, Enum):
    GOOD_PROGRESS = "GOOD_PROGRESS"
    PARTIAL_PROGRESS = "PARTIAL_PROGRESS"
    NO_PROGRESS = "NO_PROGRESS"
    REGRESSION = "REGRESSION"


class BlockerValidationVerdict(str, Enum):
    REAL_BLOCKER = "REAL_BLOCKER"
    FALSE_BLOCKER = "FALSE_BLOCKER"


class EvidenceDiagnosticStatus(str, Enum):
    PASS = "PASS"
    FAIL = "FAIL"
    SKIPPED_BY_POLICY = "SKIPPED_BY_POLICY"
    ENVIRONMENT_UNAVAILABLE = "ENVIRONMENT_UNAVAILABLE"
    EVIDENCE_NOT_REPRODUCIBLE = "EVIDENCE_NOT_REPRODUCIBLE"
    REVIEW_ENVIRONMENT_INVALID = "REVIEW_ENVIRONMENT_INVALID"


class PrimaryProvider(str, Enum):
    CODEX = "codex"
    ANTIGRAVITY = "antigravity"


PRIMARY_PROVIDERS: set[str] = {PrimaryProvider.CODEX.value, PrimaryProvider.ANTIGRAVITY.value}


class SchedulerMode(str, Enum):
    RUN = "RUN"
    DRAIN = "DRAIN"
    WAIT = "WAIT"


class ProviderHealthStatus(str, Enum):
    AVAILABLE = "available"
    TEMPORARILY_UNAVAILABLE = "temporarily_unavailable"
    EXHAUSTED = "exhausted"
    DEGRADED = "degraded"


class ProviderResultClass(str, Enum):
    SUCCESS = "success"
    TRANSIENT_ERROR = "transient_error"
    QUOTA_LIMIT = "quota_limit"
    RATE_LIMIT = "rate_limit"
    AUTH_ERROR = "auth_error"
    TIMEOUT = "timeout"
    MALFORMED_OUTPUT = "malformed_output"
    CANCELLED = "cancelled"
    POLICY_DENIED = "policy_denied"
    UNSAFE_BINDING = "unsafe_binding"
    UNKNOWN_ERROR = "unknown_error"
    BUDGET_DENIAL = "budget_denial"
    POLICY_DENIAL = "policy_denial"
    BUDGET_BREACH = "budget_breach"


class CapacitySignalSource(str, Enum):
    HEADER_RETRY_AFTER = "header_retry_after"
    RESPONSE_BODY_TIMESTAMP = "response_body_timestamp"
    UNKNOWN = "unknown"


class LockSafetyStatus(str, Enum):
    SAFE_ORPHANED = "SAFE_ORPHANED"
    ACTIVE_OWNER = "ACTIVE_OWNER"
    UNCERTAIN = "UNCERTAIN"
    EXTERNAL_OR_INVALID = "EXTERNAL_OR_INVALID"


class GitOperationStatus(str, Enum):
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    INTERRUPTED = "INTERRUPTED"
    RECOVERED = "RECOVERED"


class ReviewStatus(str, Enum):
    REVIEW_PENDING = "REVIEW_PENDING"
    REVIEW_RUNNING = "REVIEW_RUNNING"
    REVIEW_COMPLETED = "REVIEW_COMPLETED"
    REVIEW_FAILED = "REVIEW_FAILED"
    REVIEW_TIMED_OUT = "REVIEW_TIMED_OUT"


class ReviewVerdict(str, Enum):
    READY_TO_MERGE = "READY_TO_MERGE"
    CHANGES_REQUIRED = "CHANGES_REQUIRED"


class FindingSeverity(str, Enum):
    BLOCKER = "BLOCKER"
    MAJOR = "MAJOR"
    MINOR = "MINOR"


class AuditStatus(str, Enum):
    AUDIT_PENDING = "AUDIT_PENDING"
    AUDIT_RUNNING = "AUDIT_RUNNING"
    AUDIT_COMPLETED = "AUDIT_COMPLETED"
    AUDIT_BLOCKED = "AUDIT_BLOCKED"
    AUDIT_FAILED = "AUDIT_FAILED"
    AUDIT_TIMED_OUT = "AUDIT_TIMED_OUT"


class AuditRiskLevel(str, Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class AuditFindingSeverity(str, Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class EventType(str, Enum):
    PROJECT_REGISTERED = "PROJECT_REGISTERED"
    PROJECT_UPDATED = "PROJECT_UPDATED"
    CHANGE_DISCOVERED = "CHANGE_DISCOVERED"
    READINESS_EVALUATED = "READINESS_EVALUATED"
    WORK_BOUND = "WORK_BOUND"
    SYNC_FAILED = "SYNC_FAILED"
    SYNC_RECONCILED = "SYNC_RECONCILED"
    STATUS_CHECKED = "STATUS_CHECKED"
    JOB_QUEUED = "JOB_QUEUED"
    JOB_RUNNING = "JOB_RUNNING"
    JOB_CHECKS_RUNNING = "JOB_CHECKS_RUNNING"
    JOB_CHECKS_PASSED = "JOB_CHECKS_PASSED"
    JOB_CHECKS_FAILED = "JOB_CHECKS_FAILED"
    JOB_REVIEW_RUNNING = "JOB_REVIEW_RUNNING"
    JOB_AUDIT_RUNNING = "JOB_AUDIT_RUNNING"
    JOB_AUDIT_COMPLETED = "JOB_AUDIT_COMPLETED"
    JOB_AUDIT_BLOCKED = "JOB_AUDIT_BLOCKED"
    JOB_AUDIT_FAILED = "JOB_AUDIT_FAILED"
    JOB_READY_TO_MERGE = "JOB_READY_TO_MERGE"
    JOB_CHANGES_REQUIRED = "JOB_CHANGES_REQUIRED"
    JOB_WAITING_CAPACITY = "JOB_WAITING_CAPACITY"
    JOB_FAILED = "JOB_FAILED"
    JOB_CANCELLED = "JOB_CANCELLED"
    JOB_TIMEOUT = "JOB_TIMEOUT"
    INCOMPLETE_TASKS = "INCOMPLETE_TASKS"
    REVIEW_POLICY_VIOLATION = "REVIEW_POLICY_VIOLATION"
    REVIEW_TIMEOUT = "REVIEW_TIMEOUT"
    AUDIT_TIMEOUT = "AUDIT_TIMEOUT"
    CANDIDATE_SHA_MISMATCH = "CANDIDATE_SHA_MISMATCH"
    UNAUTHORIZED_REVIEWER_MUTATION = "UNAUTHORIZED_REVIEWER_MUTATION"
    UNAUTHORIZED_AUDITOR_MUTATION = "UNAUTHORIZED_AUDITOR_MUTATION"
    MALFORMED_REVIEW_OUTPUT = "MALFORMED_REVIEW_OUTPUT"
    AUDIT_MALFORMED_OUTPUT = "AUDIT_MALFORMED_OUTPUT"
    SCHEDULER_MODE_CHANGED = "SCHEDULER_MODE_CHANGED"
    PRIMARY_CAPACITY_EXHAUSTED = "PRIMARY_CAPACITY_EXHAUSTED"
    PRIMARY_CAPACITY_RECOVERED = "PRIMARY_CAPACITY_RECOVERED"
    PROVIDER_HEALTH_UPDATED = "PROVIDER_HEALTH_UPDATED"
    PROVIDER_PROBE_FAILED = "PROVIDER_PROBE_FAILED"
    DAEMON_RESTARTED = "DAEMON_RESTARTED"
    JOB_INTERRUPTED = "JOB_INTERRUPTED"
    JOB_RECOVERED = "JOB_RECOVERED"
    WORKTREE_LOCK_RECOVERED = "WORKTREE_LOCK_RECOVERED"
    WORKTREE_RECOVERY_SNAPSHOT = "WORKTREE_RECOVERY_SNAPSHOT"
    HUMAN_RESOLUTION = "HUMAN_RESOLUTION"
    LEGACY_CANDIDATE_RECORD_ADOPTED = "LEGACY_CANDIDATE_RECORD_ADOPTED"
    LEGACY_CANDIDATE_REF_ADOPTED = "LEGACY_CANDIDATE_REF_ADOPTED"
    RECOVERY_BLOCKED = "RECOVERY_BLOCKED"
    FALLBACK_INVOKED = "FALLBACK_INVOKED"
    BUDGET_RESERVED = "BUDGET_RESERVED"
    BUDGET_SETTLED = "BUDGET_SETTLED"
    BUDGET_CAP_EXCEEDED = "BUDGET_CAP_EXCEEDED"
    BUDGET_BREACH_DETECTED = "BUDGET_BREACH_DETECTED"
    FALLBACK_MODEL_SELECTED = "FALLBACK_MODEL_SELECTED"
    FALLBACK_DENIED = "FALLBACK_DENIED"
    ATTEMPT_STARTED = "ATTEMPT_STARTED"
    ATTEMPT_COMPLETED = "ATTEMPT_COMPLETED"
    COMPLETION_VERIFIED = "COMPLETION_VERIFIED"
    COMPLETION_REJECTED = "COMPLETION_REJECTED"
    BLOCKER_CLAIMED = "BLOCKER_CLAIMED"
    BLOCKER_VALIDATED = "BLOCKER_VALIDATED"
    CONTINUATION_DECIDED = "CONTINUATION_DECIDED"
    CORRECTIVE_RETRY_ISSUED = "CORRECTIVE_RETRY_ISSUED"
    AGENT_REASSIGNED = "AGENT_REASSIGNED"
    AGENT_PING_PONG_EXHAUSTED = "AGENT_PING_PONG_EXHAUSTED"
    HANDOFF_CREATED = "HANDOFF_CREATED"
    HANDOFF_CONSUMED = "HANDOFF_CONSUMED"
    CANDIDATE_MANIFEST_CREATED = "CANDIDATE_MANIFEST_CREATED"
    REVIEW_VISIBILITY_INVALID = "REVIEW_VISIBILITY_INVALID"
    EVIDENCE_DIAGNOSTIC_RECORDED = "EVIDENCE_DIAGNOSTIC_RECORDED"
    JOB_NEEDS_HUMAN = "JOB_NEEDS_HUMAN"
    ORCHESTRATION_STARTED = "ORCHESTRATION_STARTED"
    ORCHESTRATION_STAGE_TRANSITIONED = "ORCHESTRATION_STAGE_TRANSITIONED"
    ORCHESTRATION_STOPPED = "ORCHESTRATION_STOPPED"
    ORCHESTRATION_RESUMED = "ORCHESTRATION_RESUMED"
    ORCHESTRATION_RECOVERED = "ORCHESTRATION_RECOVERED"
    CANDIDATE_FROZEN = "CANDIDATE_FROZEN"
    CANDIDATE_SUPERSEDED = "CANDIDATE_SUPERSEDED"
    EXTERNAL_ACTION_RESERVED = "EXTERNAL_ACTION_RESERVED"
    EXTERNAL_ACTION_COMPLETED = "EXTERNAL_ACTION_COMPLETED"
    PR_PREPARED = "PR_PREPARED"
    READY_FOR_HUMAN_MERGE = "READY_FOR_HUMAN_MERGE"
    PREVIEW_REQUESTED = "PREVIEW_REQUESTED"
    PREVIEW_BUILDING = "PREVIEW_BUILDING"
    PREVIEW_READY = "PREVIEW_READY"
    PREVIEW_FAILED = "PREVIEW_FAILED"
    PREVIEW_TERMINATED = "PREVIEW_TERMINATED"
    VALIDATION_SUBMITTED = "VALIDATION_SUBMITTED"
    VALIDATION_INVALIDATED = "VALIDATION_INVALIDATED"
    VALIDATION_REQUIRED_GATE_BLOCKED = "VALIDATION_REQUIRED_GATE_BLOCKED"
    OPERATOR_ACTION_REQUESTED = "OPERATOR_ACTION_REQUESTED"
    OPERATOR_ACTION_EXECUTED = "OPERATOR_ACTION_EXECUTED"
    OPERATOR_ACTION_REJECTED = "OPERATOR_ACTION_REJECTED"
    OPERATOR_ACTION_FAILED = "OPERATOR_ACTION_FAILED"
    SAME_SHA_RETRY_SUPPRESSED = "SAME_SHA_RETRY_SUPPRESSED"
    LIGHTWEIGHT_RECONCILIATION_PERFORMED = "LIGHTWEIGHT_RECONCILIATION_PERFORMED"
    PREMIUM_PROVIDER_ASSIGNED = "PREMIUM_PROVIDER_ASSIGNED"
    PROVIDER_DRAIN_TRANSITION = "PROVIDER_DRAIN_TRANSITION"
    REVIEWER_INDEPENDENCE_BLOCKED = "REVIEWER_INDEPENDENCE_BLOCKED"
    PROVIDER_EFFICIENCY_RECORDED = "PROVIDER_EFFICIENCY_RECORDED"
    MERGE_DETECTED = "MERGE_DETECTED"
    POST_MERGE_STARTED = "POST_MERGE_STARTED"
    OPEN_SPEC_SYNCED = "OPEN_SPEC_SYNCED"
    OPEN_SPEC_ARCHIVED = "OPEN_SPEC_ARCHIVED"
    ISSUE_CLOSED = "ISSUE_CLOSED"
    PROJECT_ITEM_DONE = "PROJECT_ITEM_DONE"
    BRANCH_CLEANED = "BRANCH_CLEANED"
    WORKTREE_CLEANED = "WORKTREE_CLEANED"
    LOCKS_RELEASED = "LOCKS_RELEASED"
    POST_MERGE_COMPLETED = "POST_MERGE_COMPLETED"
    PROJECT_ONBOARDED = "PROJECT_ONBOARDED"
    CONTEXT_DISCOVERED = "CONTEXT_DISCOVERED"
    WORK_ITEM_CREATED = "WORK_ITEM_CREATED"
    WORK_ITEM_UPDATED = "WORK_ITEM_UPDATED"
    WORK_ITEM_PREPARED = "WORK_ITEM_PREPARED"
    WORK_ITEM_QUESTION_ANSWERED = "WORK_ITEM_QUESTION_ANSWERED"
    WORK_ITEM_STARTED = "WORK_ITEM_STARTED"
    WORK_ITEM_CANCELLED = "WORK_ITEM_CANCELLED"


class PreviewStatus(str, Enum):
    """Durable lifecycle states for an isolated container preview session."""

    REQUESTED = "REQUESTED"
    BUILDING = "BUILDING"
    STARTING = "STARTING"
    PROBING = "PROBING"
    READY = "READY"
    FAILED = "FAILED"
    TERMINATED = "TERMINATED"


class ValidationVerdict(str, Enum):
    """Authoritative outcome of a visual / human validation run."""

    PASS = "PASS"
    FAIL = "FAIL"


class OrchestrationStage(str, Enum):
    ADMITTED = "ADMITTED"
    PREPARING_EXECUTION = "PREPARING_EXECUTION"
    IMPLEMENTING = "IMPLEMENTING"
    EVALUATING_ATTEMPT = "EVALUATING_ATTEMPT"

    RUNNING_CHECKS = "RUNNING_CHECKS"
    FREEZING_CANDIDATE = "FREEZING_CANDIDATE"
    COMPLEMENTARY_REVIEW = "COMPLEMENTARY_REVIEW"
    REVIEW_REMEDIATION = "REVIEW_REMEDIATION"
    INDEPENDENT_AUDIT = "INDEPENDENT_AUDIT"
    AUDIT_REMEDIATION = "AUDIT_REMEDIATION"
    PREPARING_PR = "PREPARING_PR"
    PR_PREPARED = "PR_PREPARED"
    POST_MERGE_RECONCILING = "POST_MERGE_RECONCILING"
    COMPLETED = "COMPLETED"


class OrchestrationStopOutcome(str, Enum):
    READY_FOR_HUMAN_MERGE = "READY_FOR_HUMAN_MERGE"
    COMPLETED = "COMPLETED"
    WAITING_CAPACITY = "WAITING_CAPACITY"
    WAITING_EXTERNAL = "WAITING_EXTERNAL"
    NEEDS_HUMAN = "NEEDS_HUMAN"
    CANCELLED = "CANCELLED"
    FAILED = "FAILED"


class HumanGate(str, Enum):
    READY_FOR_HUMAN_MERGE = "READY_FOR_HUMAN_MERGE"
    NEEDS_HUMAN = "NEEDS_HUMAN"


class ExternalActionType(str, Enum):
    BRANCH_PUSH = "BRANCH_PUSH"
    PR_CREATE = "PR_CREATE"


class PullRequestLookupState(str, Enum):
    """Authoritative outcome of a remote pull-request lookup."""

    NOT_FOUND = "NOT_FOUND"
    FOUND_EXACT = "FOUND_EXACT"
    UNOBSERVABLE = "UNOBSERVABLE"
    AMBIGUOUS = "AMBIGUOUS"
    PR_UPDATE = "PR_UPDATE"


class ExternalActionStatus(str, Enum):
    RESERVED = "RESERVED"
    EXECUTING = "EXECUTING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    AMBIGUOUS = "AMBIGUOUS"


class OperatorActionType(str, Enum):
    """Canonical action types supported by the Operator Control Plane."""

    CONTINUE = "CONTINUE"
    RESUME = "RESUME"
    RETRY = "RETRY"
    REASSIGN = "REASSIGN"
    RESOLVE_GATE = "RESOLVE_GATE"
    CANCEL = "CANCEL"
    START_PREVIEW = "START_PREVIEW"
    TEARDOWN_PREVIEW = "TEARDOWN_PREVIEW"
    RECOVER_LOCKS = "RECOVER_LOCKS"
    RECONCILE_POST_MERGE = "RECONCILE_POST_MERGE"


class OperatorActionStatus(str, Enum):
    """Durable execution outcome states for an operator action request."""

    ACCEPTED = "ACCEPTED"
    COMPLETED = "COMPLETED"
    REJECTED = "REJECTED"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"


class OperatorActionErrorCode(str, Enum):
    """Structured machine-readable error codes for rejected or failed operator actions."""

    ACTION_NOT_ALLOWED = "ACTION_NOT_ALLOWED"
    STALE_OPERATOR_STATE = "STALE_OPERATOR_STATE"
    AUTHORITY_MISMATCH = "AUTHORITY_MISMATCH"
    PROVIDER_UNAVAILABLE = "PROVIDER_UNAVAILABLE"
    BUDGET_BLOCKED = "BUDGET_BLOCKED"
    RECOVERY_REQUIRED = "RECOVERY_REQUIRED"
    ACTION_ALREADY_COMPLETED = "ACTION_ALREADY_COMPLETED"
    INVALID_ACTION_PARAMETERS = "INVALID_ACTION_PARAMETERS"
    ACTION_EXECUTION_FAILED = "ACTION_EXECUTION_FAILED"


class ActionRiskLevel(str, Enum):
    """Risk/impact classification for operator actions."""

    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class QueuePriority(str, Enum):
    """Explicit priority levels for candidate work in the scheduler queue."""

    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    NORMAL = "NORMAL"
    LOW = "LOW"


class AdmissionDecision(str, Enum):
    """Outcome decision for a scheduler admission evaluation."""

    ADMITTED = "ADMITTED"
    REFUSED = "REFUSED"
    SKIPPED = "SKIPPED"


class AdmissionRefusalCode(str, Enum):
    """Structured refusal reason codes for scheduler admission evaluation."""

    NOT_READY = "NOT_READY"
    ROADMAP_PREDECESSOR_INCOMPLETE = "ROADMAP_PREDECESSOR_INCOMPLETE"
    DEPENDENCY_BLOCKED = "DEPENDENCY_BLOCKED"
    PROVIDER_DRAIN = "PROVIDER_DRAIN"
    PROVIDER_WAIT = "PROVIDER_WAIT"
    PROVIDER_UNAVAILABLE = "PROVIDER_UNAVAILABLE"
    BUDGET_BLOCKED = "BUDGET_BLOCKED"
    GLOBAL_CONCURRENCY_LIMIT = "GLOBAL_CONCURRENCY_LIMIT"
    PROJECT_CONCURRENCY_LIMIT = "PROJECT_CONCURRENCY_LIMIT"
    CHANGE_ALREADY_ACTIVE = "CHANGE_ALREADY_ACTIVE"
    ALREADY_ADMITTED = "ALREADY_ADMITTED"
    INVALID_BINDING = "INVALID_BINDING"
    SPEC_INVALID = "SPEC_INVALID"
    WORKSPACE_PREFLIGHT_FAILED = "WORKSPACE_PREFLIGHT_FAILED"
    WORKSPACE_ERROR = "WORKSPACE_ERROR"
    EVALUATION_ERROR = "EVALUATION_ERROR"


class TaskClass(str, Enum):
    """Deterministic classification of task / implementation attempts."""

    ROUTINE_IMPLEMENTATION = "ROUTINE_IMPLEMENTATION"
    ORDINARY_REMEDIATION = "ORDINARY_REMEDIATION"
    TEST_FIX = "TEST_FIX"
    BOOKKEEPING_RECONCILIATION = "BOOKKEEPING_RECONCILIATION"
    EVIDENCE_RECONCILIATION = "EVIDENCE_RECONCILIATION"
    ARCHITECTURE = "ARCHITECTURE"
    UX_VISUAL_QA = "UX_VISUAL_QA"
    PLATFORM_RECOVERY = "PLATFORM_RECOVERY"
    SPECIALIZED = "SPECIALIZED"


class PremiumProviderReasonCode(str, Enum):
    """Explicit reasons authorized for selecting premium constrained providers (e.g. Antigravity)."""

    ARCHITECTURE_REQUIRED = "ARCHITECTURE_REQUIRED"
    UX_VISUAL_QA = "UX_VISUAL_QA"
    PLATFORM_RECOVERY = "PLATFORM_RECOVERY"
    CODEX_NON_CONVERGENCE = "CODEX_NON_CONVERGENCE"
    SPECIALIZED_REASON = "SPECIALIZED_REASON"
    PREMIUM_PROVIDER_NOT_REQUIRED = "PREMIUM_PROVIDER_NOT_REQUIRED"


class AttemptProductivityClass(str, Enum):
    """Deterministic classification of provider execution attempt outcomes."""

    SUBSTANTIVE_PROGRESS = "SUBSTANTIVE_PROGRESS"
    VALID_CORRECTIVE_WORK = "VALID_CORRECTIVE_WORK"
    BOOKKEEPING_ONLY = "BOOKKEEPING_ONLY"
    EVIDENCE_SYNC_ONLY = "EVIDENCE_SYNC_ONLY"
    SAME_SHA_NO_PROGRESS = "SAME_SHA_NO_PROGRESS"
    DUPLICATE_RETRY = "DUPLICATE_RETRY"
    PLATFORM_REPAIR = "PLATFORM_REPAIR"
    UX_VISUAL_REVIEW = "UX_VISUAL_REVIEW"
    ARCHITECTURE_WORK = "ARCHITECTURE_WORK"
    PROVIDER_FAILURE = "PROVIDER_FAILURE"
    OTHER = "OTHER"


class AuthEventType(str, Enum):
    """Security-relevant authentication event types for audit trail."""

    LOGIN_SUCCEEDED = "LOGIN_SUCCEEDED"
    LOGIN_REJECTED = "LOGIN_REJECTED"
    AUTHORIZATION_DENIED = "AUTHORIZATION_DENIED"
    LOGOUT = "LOGOUT"
    SESSION_EXPIRED = "SESSION_EXPIRED"
    SESSION_REVOKED = "SESSION_REVOKED"


class OperatorAuthDecision(str, Enum):
    """Deterministic authorization decision codes."""

    AUTHORIZED = "AUTHORIZED"
    IDENTITY_NOT_ALLOWLISTED = "IDENTITY_NOT_ALLOWLISTED"
    IDENTITY_DISABLED = "IDENTITY_DISABLED"
    INVALID_IDENTITY = "INVALID_IDENTITY"
    SESSION_EXPIRED = "SESSION_EXPIRED"
    SESSION_REVOKED = "SESSION_REVOKED"
    NO_SESSION = "NO_SESSION"


WorkItemPriority = QueuePriority
