"""Domain enumeration types for mini me."""

from enum import Enum


class ProjectStatus(str, Enum):
    ACTIVE = "ACTIVE"
    DISABLED = "DISABLED"
    ARCHIVED = "ARCHIVED"


class ChangeStatus(str, Enum):
    DISCOVERED = "DISCOVERED"
    READY = "READY"
    IN_PROGRESS = "IN_PROGRESS"
    BLOCKED = "BLOCKED"
    DONE = "DONE"
    CANCELLED = "CANCELLED"


class ReadinessState(str, Enum):
    READY = "READY"
    NOT_READY = "NOT_READY"
    BLOCKED = "BLOCKED"


class AgentRole(str, Enum):
    IMPLEMENTER = "implementer"
    REVIEWER = "reviewer"
    AUDITOR = "auditor"
    HELPER = "helper"


class JobStatus(str, Enum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    CHECKS_RUNNING = "CHECKS_RUNNING"
    CHECKS_PASSED = "CHECKS_PASSED"
    CHECKS_FAILED = "CHECKS_FAILED"
    REVIEW_RUNNING = "REVIEW_RUNNING"
    AUDIT_RUNNING = "AUDIT_RUNNING"
    READY_TO_MERGE = "READY_TO_MERGE"
    AUDIT_BLOCKED = "AUDIT_BLOCKED"
    CHANGES_REQUIRED = "CHANGES_REQUIRED"
    WAITING_CAPACITY = "WAITING_CAPACITY"
    RECOVERY_BLOCKED = "RECOVERY_BLOCKED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class PrimaryProvider(str, Enum):
    CODEX = "codex"
    ANTIGRAVITY = "antigravity"


PRIMARY_PROVIDERS: set[str] = {PrimaryProvider.CODEX.value, PrimaryProvider.ANTIGRAVITY.value}


class SchedulerMode(str, Enum):
    RUN = "RUN"
    DRAIN = "DRAIN"
    WAIT = "WAIT"


class ProviderHealthStatus(str, Enum):
    AVAILABLE = "available"
    TEMPORARILY_UNAVAILABLE = "temporarily_unavailable"
    EXHAUSTED = "exhausted"
    DEGRADED = "degraded"


class ProviderResultClass(str, Enum):
    SUCCESS = "success"
    TRANSIENT_ERROR = "transient_error"
    QUOTA_LIMIT = "quota_limit"
    RATE_LIMIT = "rate_limit"
    AUTH_ERROR = "auth_error"
    TIMEOUT = "timeout"
    MALFORMED_OUTPUT = "malformed_output"
    CANCELLED = "cancelled"
    POLICY_DENIED = "policy_denied"
    UNSAFE_BINDING = "unsafe_binding"
    UNKNOWN_ERROR = "unknown_error"
    BUDGET_DENIAL = "budget_denial"
    POLICY_DENIAL = "policy_denial"
    BUDGET_BREACH = "budget_breach"


class CapacitySignalSource(str, Enum):
    HEADER_RETRY_AFTER = "header_retry_after"
    RESPONSE_BODY_TIMESTAMP = "response_body_timestamp"
    UNKNOWN = "unknown"


class LockSafetyStatus(str, Enum):
    SAFE_ORPHANED = "SAFE_ORPHANED"
    ACTIVE_OWNER = "ACTIVE_OWNER"
    UNCERTAIN = "UNCERTAIN"
    EXTERNAL_OR_INVALID = "EXTERNAL_OR_INVALID"


class GitOperationStatus(str, Enum):
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    INTERRUPTED = "INTERRUPTED"
    RECOVERED = "RECOVERED"


class ReviewStatus(str, Enum):
    REVIEW_PENDING = "REVIEW_PENDING"
    REVIEW_RUNNING = "REVIEW_RUNNING"
    REVIEW_COMPLETED = "REVIEW_COMPLETED"
    REVIEW_FAILED = "REVIEW_FAILED"
    REVIEW_TIMED_OUT = "REVIEW_TIMED_OUT"


class ReviewVerdict(str, Enum):
    READY_TO_MERGE = "READY_TO_MERGE"
    CHANGES_REQUIRED = "CHANGES_REQUIRED"


class FindingSeverity(str, Enum):
    BLOCKER = "BLOCKER"
    MAJOR = "MAJOR"
    MINOR = "MINOR"


class AuditStatus(str, Enum):
    AUDIT_PENDING = "AUDIT_PENDING"
    AUDIT_RUNNING = "AUDIT_RUNNING"
    AUDIT_COMPLETED = "AUDIT_COMPLETED"
    AUDIT_BLOCKED = "AUDIT_BLOCKED"
    AUDIT_FAILED = "AUDIT_FAILED"
    AUDIT_TIMED_OUT = "AUDIT_TIMED_OUT"


class AuditRiskLevel(str, Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class AuditFindingSeverity(str, Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class EventType(str, Enum):
    PROJECT_REGISTERED = "PROJECT_REGISTERED"
    PROJECT_UPDATED = "PROJECT_UPDATED"
    CHANGE_DISCOVERED = "CHANGE_DISCOVERED"
    READINESS_EVALUATED = "READINESS_EVALUATED"
    WORK_BOUND = "WORK_BOUND"
    SYNC_FAILED = "SYNC_FAILED"
    SYNC_RECONCILED = "SYNC_RECONCILED"
    STATUS_CHECKED = "STATUS_CHECKED"
    JOB_QUEUED = "JOB_QUEUED"
    JOB_RUNNING = "JOB_RUNNING"
    JOB_CHECKS_RUNNING = "JOB_CHECKS_RUNNING"
    JOB_CHECKS_PASSED = "JOB_CHECKS_PASSED"
    JOB_CHECKS_FAILED = "JOB_CHECKS_FAILED"
    JOB_REVIEW_RUNNING = "JOB_REVIEW_RUNNING"
    JOB_AUDIT_RUNNING = "JOB_AUDIT_RUNNING"
    JOB_AUDIT_COMPLETED = "JOB_AUDIT_COMPLETED"
    JOB_AUDIT_BLOCKED = "JOB_AUDIT_BLOCKED"
    JOB_AUDIT_FAILED = "JOB_AUDIT_FAILED"
    JOB_READY_TO_MERGE = "JOB_READY_TO_MERGE"
    JOB_CHANGES_REQUIRED = "JOB_CHANGES_REQUIRED"
    JOB_WAITING_CAPACITY = "JOB_WAITING_CAPACITY"
    JOB_FAILED = "JOB_FAILED"
    JOB_CANCELLED = "JOB_CANCELLED"
    JOB_TIMEOUT = "JOB_TIMEOUT"
    INCOMPLETE_TASKS = "INCOMPLETE_TASKS"
    REVIEW_POLICY_VIOLATION = "REVIEW_POLICY_VIOLATION"
    REVIEW_TIMEOUT = "REVIEW_TIMEOUT"
    AUDIT_TIMEOUT = "AUDIT_TIMEOUT"
    CANDIDATE_SHA_MISMATCH = "CANDIDATE_SHA_MISMATCH"
    UNAUTHORIZED_REVIEWER_MUTATION = "UNAUTHORIZED_REVIEWER_MUTATION"
    UNAUTHORIZED_AUDITOR_MUTATION = "UNAUTHORIZED_AUDITOR_MUTATION"
    MALFORMED_REVIEW_OUTPUT = "MALFORMED_REVIEW_OUTPUT"
    AUDIT_MALFORMED_OUTPUT = "AUDIT_MALFORMED_OUTPUT"
    SCHEDULER_MODE_CHANGED = "SCHEDULER_MODE_CHANGED"
    PRIMARY_CAPACITY_EXHAUSTED = "PRIMARY_CAPACITY_EXHAUSTED"
    PRIMARY_CAPACITY_RECOVERED = "PRIMARY_CAPACITY_RECOVERED"
    PROVIDER_HEALTH_UPDATED = "PROVIDER_HEALTH_UPDATED"
    PROVIDER_PROBE_FAILED = "PROVIDER_PROBE_FAILED"
    DAEMON_RESTARTED = "DAEMON_RESTARTED"
    JOB_INTERRUPTED = "JOB_INTERRUPTED"
    JOB_RECOVERED = "JOB_RECOVERED"
    WORKTREE_LOCK_RECOVERED = "WORKTREE_LOCK_RECOVERED"
    RECOVERY_BLOCKED = "RECOVERY_BLOCKED"
    FALLBACK_INVOKED = "FALLBACK_INVOKED"
    BUDGET_RESERVED = "BUDGET_RESERVED"
    BUDGET_SETTLED = "BUDGET_SETTLED"
    BUDGET_CAP_EXCEEDED = "BUDGET_CAP_EXCEEDED"
    BUDGET_BREACH_DETECTED = "BUDGET_BREACH_DETECTED"
    FALLBACK_MODEL_SELECTED = "FALLBACK_MODEL_SELECTED"
    FALLBACK_DENIED = "FALLBACK_DENIED"
